### PR TITLE
Further Microblog/Entry Support

### PR DESCRIPTION
**Pull request by olorin99**
Added
- Viewing posts in magazine/user feeds.
- Edit posts and post comments.
- Edit entries entry comments .
- Delete posts and post comments.
- Delete entries and entry comments.
- Edit/Delete buttons are greyed out on feed page.
- Edit/Delete buttons are greyed out if logged in user is not op.

### CODE REVIEW

**Review by jwr1 — CHANGES_REQUESTED** [review]
LGTM, I just have one small change. Could you have it so when editing entries/posts/comments that they get prefilled with the original content? This could be an `initEdit` function parameter in the `ActionBar` widget that fetches the original content and sets the text controller with it.

**Review by jwr1 — CHANGES_REQUESTED** [review]
One other thing I noticed is that the edit/delete menu still shows up and is clickable even when the thread/post/comment was made by someone else.

**Review by jwr1 — CHANGES_REQUESTED** [review]
Also (hopefully this is the last thing), when the edit and delete buttons shouldn't be available, like on the feed view or when logged out, the delete button is greyed out correctly, but the edit button is not.

image

**Comment by olorin99** [comment]
> One other thing I noticed is that the edit/delete menu still shows up and is clickable even when the thread/post/comment was made by someone else.

In order to check if logged in user is the OP, is the logged in userID stored somewhere?
I can see "_selectedAccount" in SettingsController. Would this be the best variable to use for comparisons?

**Comment by jwr1** [comment]
> > One other thing I noticed is that the edit/delete menu still shows up and is clickable even when the thread/post/comment was made by someone else.
> 
> In order to check if logged in user is the OP, is the logged in userID stored somewhere? I can see "_selectedAccount" in SettingsController. Would this be the best variable to use for comparisons?

Yes, that would work.

**Comment by jwr1** [comment]
`selectedAccount` isn't the user id though, it's the username (like @hello@kbin.earth, instead of 53198).

**Comment by jwr1** [comment]
It looks like the username, from the API, for non federated users is just the username itself (no at symbols or hosts), so you could just check that the user.username field in content matches the part before the `@` in `selectedAccount`.

**Comment by olorin99** [comment]
@jwr1 Should be good to go now.

**Review by jwr1 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
