### PR TITLE
Adds highlighting for user mentions.

### PR DESCRIPTION
**Pull request by olorin99**
Replaces @mentions in markdown with a inkwell that routes to the users profile when clicked.

### CODE REVIEW

**Comment by olorin99** [comment]
Lol didn't pull before pushing this.

**Comment by jwr1** [comment]
The functionality of user/magazine mentions should be done, but I'm still working on the visual indicator. At the moment, this is how it looks: 

image

**Comment by jwr1** [comment]
It should be done now, if you want to try it out or make suggestions.

**Comment by olorin99** [comment]
Looks great. One thing I noted is that apparently magazine mentions can also be @magazine. The main use case seems to be [mastodon users posting in lemmy communities](https://kbin.social/m/showerthoughts@lemmy.world/p/4515910/At-some-point-in-your-childhood-you-and-your-friends)

However it seems to conflict with user mentions like at https://kbin.social/m/kbinMeta/t/828882/So-what-s-going-on where the @tech links to a user instead of the magazine. So it is probably better not to handle that case.

**Comment by jwr1** [comment]
I hadn't thought of that. Microblogging is half of kbin, but I don't think the use cases outway the weird problems it could cause. We can easily add it later on though, if we think it'd be useful.

**Comment by olorin99** [comment]
Agreed. In the few cases I could find the link to the magazine is right there anyway next to the username so there's little to no impact on usability.

**Pull request closed without merging**
